<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-23T13:09:52 IST" name="Tata_EMS_Suite" finished-at="2023-02-23T13:10:33 IST" duration-ms="40875">
    <groups>
    </groups>
    <test started-at="2023-02-23T13:09:52 IST" name="Tata_EMS_Test" finished-at="2023-02-23T13:10:33 IST" duration-ms="40875">
      <class name="tata_EMS_Project_Test_Cases.Login_Test">
        <test-method is-config="true" signature="applicationSetup()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:09:53 IST" name="applicationSetup" finished-at="2023-02-23T13:10:08 IST" duration-ms="15331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationSetup -->
        <test-method signature="Test01_Verifying_login_with_InValidDetails()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:10:08 IST" name="Test01_Verifying_login_with_InValidDetails" finished-at="2023-02-23T13:10:10 IST" duration-ms="1457" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://staging.netscribes.co/tata_ems_testing/admin/d2b5316eadb139ea4a091aeca9ec5bd3] but found [https://staging.netscribes.co/tata_ems_testing/admin/dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://staging.netscribes.co/tata_ems_testing/admin/d2b5316eadb139ea4a091aeca9ec5bd3] but found [https://staging.netscribes.co/tata_ems_testing/admin/dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tata_EMS_Project_Test_Cases.Login_Test.Test01_Verifying_login_with_InValidDetails(Login_Test.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test01_Verifying_login_with_InValidDetails -->
        <test-method is-config="true" signature="applicationClose()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:10:10 IST" name="applicationClose" finished-at="2023-02-23T13:10:13 IST" duration-ms="2227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationClose -->
        <test-method is-config="true" signature="applicationSetup()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:10:13 IST" name="applicationSetup" finished-at="2023-02-23T13:10:23 IST" duration-ms="10450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationSetup -->
        <test-method signature="Test01_Verifying_login_with_ValidDetails()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:10:23 IST" name="Test01_Verifying_login_with_ValidDetails" finished-at="2023-02-23T13:10:30 IST" duration-ms="7056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test01_Verifying_login_with_ValidDetails -->
        <test-method is-config="true" signature="applicationClose()[pri:0, instance:tata_EMS_Project_Test_Cases.Login_Test@63376bed]" started-at="2023-02-23T13:10:30 IST" name="applicationClose" finished-at="2023-02-23T13:10:33 IST" duration-ms="2860" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applicationClose -->
      </class> <!-- tata_EMS_Project_Test_Cases.Login_Test -->
    </test> <!-- Tata_EMS_Test -->
  </suite> <!-- Tata_EMS_Suite -->
</testng-results>
